# Generated by Django 5.0.2 on 2024-02-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=70)),
                ('amount', models.IntegerField()),
                ('is_cure', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.cure')),
            ],
        ),
    ]
